---
title: "O problema do Poeta - Abordagem generalista"
format: html
---

# Modelagem descritiva:

O exemplo apresentado a seguir descreve a situação de um poeta que mora há dez anos numa floresta de sua propriedade. Além de escrever poesia, o poeta também maneja sua floresta para obter uma receita adicional para sobreviver. A floresta se divide da seguinte maneira:

-   40 hectares de plantações de Pinus taeda;
-   50 hectares de floresta nativa.

Em suas anotações, recopiladas meticulosamente ao longo dos últimos dez anos, constam as seguintes informações:

-   800 dias foram utilizados no manejo das plantações de Pinus taeda, gerando uma receita total acumulada de R\$ 36.000,00;

-   1.500 dias foram utilizados no manejo da floresta nativa, gerando uma receita total acumulada de R\$ 60.000,00.

O poeta quer encontrar uma forma de obter a máxima receita possível a partir da floresta, sem utilizar mais do que a metade do seu tempo, equivalente a 180 dias por ano, no manejo da mesma. Para atingir este objetivo, o poeta deve saber quantos hectares devem ser manejados anualmente de cada tipo de floresta.

## Variáveis de decisão

Como foi mencionado, o desejo do poeta é maximizar a receita advinda da sua propriedade florestal. Mas isto somente faz sentido se os recursos são finitos, ou seja, o que deve ser maximizado é a receita por unidade de tempo como, por exemplo, por ano, levando em consideração a média dos dez anos de manejo florestal que se passaram na propriedade. Formalmente, pode-se começar a escrever o objetivo do problema como segue:

-   Maximizar Z = R\$ de receita por ano

A receita simbolizada por Z pode ser proveniente da floresta de Pinus, ou da floresta nativa, ou de ambas. Portanto, uma opção natural para as variáveis é:

-   $x_1 \colon \text{número de hectares de floresta de Pinus a serem manejados}$
-   $x_2 \colon \text{número de hectares de floresta nativas a serem manejadas}$

Estas são as incógnitas. Devem ser examinados os valores possíveis de X1 e X2 para tornar o valor de Z o maior possível.

## Função objetivo

Função objetivo A função objetivo deve expressar a relação existente entre Z, que é a receita gerada pela floresta, e as variáveis de decisão X1 e X2. Para obter esta função, é preciso ter uma noção das receitas anuais de cada tipo de floresta. Como o poeta recebeu R\$ 36.000,00 dos seus 40 ha de floresta de Pinus e R\$ 60.000,00 dos seus 50 ha de floresta nativa durante os últimos 10 anos, a receita anual media foi de R\$ 90 por hectare (R\$ 90/ha/ano) para a floresta de Pinus, e de R\$ 120/ha/ano para a floresta nativa. Utilizando estes valores como medida da receita esperada pelo poeta para os próximos anos, a função objetivo pode-se ser escrita como segue:

$\max z = 90x_1 + 120x_2$

Onde as unidades de medida de cada variável e constante aparecem entre parênteses. Uma boa prática de modelagem de problemas é verificar minuciosamente a coerência de todas as expressões algébricas com respeito a suas unidades de medida. Na função objetivo, Z é expressa em reais por ano, de modo que as operações à direita do sinal de igualdade da função objetivo devem resultar em reais por ano também, como pode ser verificado. Para completar o modelo, deve-se ainda determinar quais restrições limitam as ações do poeta de modo a ajudar ele a escrever as mesmas em termos matemáticos referentes às variáveis de decisão X1 e X2.

## Restrições de área

As restrições que talvez sejam as mais simples de entender dizem respeito das áreas a serem utilizadas de cada tipo de floresta. Estas áreas não podem ser maiores do que as disponíveis. Deste modo, tem-se:

-   $x_1 ≤ 40 \text{ ha de floresta de Pinus}$
-   $x_2 ≤ 50 \text{ ha de floresta nativa}$

Nas restrições de área pode ser verificado que as unidades nas quais se expressa o lado direito das mesmas (ha) são as mesmas que as do lado esquerdo (definição das variáveis X1 e X2).

## Restrição de tempo

Quando o poeta manifestou seu desejo de não trabalhar mais do que metade do seu tempo na floresta, o que representa grosseiramente 180 dias/ano, deve-se pensar em mais uma restrição. Para escrever esta restrição em função das variáveis de decisão, devemos observar que o poeta utilizou, nos últimos 10 anos, 800 dias para manejar os 40 ha de floresta de Pinus, o que resulta em uma dedicação média de 2 dias por hectare por ano (2 dias/ha/ano). De maneira similar, 3 dias/ha/ano foi a dedicação média de tempo na floresta nativa, onde ao longo dos últimos 10 anos foram utilizados 1.500 dias para manejar os 50 ha de floresta nativa. Em termos das variáveis de decisão X1 e X2, a expressão que representa o tempo necessário para manejar floresta é:

$$
2x_1 + 3x_2
$$

a expressão que limita este tempo para um valor máximo de 180 dias/ano é:

$$
2x_1 + 3x_2 \leq 180
$$

## Condição de não-negatividade

A última restrição necessária para completar a formulação do problema estabelece que nenhuma das variáveis pode ser negativa, uma vez que elas referem-se a áreas sob manejo. Deste modo, tem-se a seguinte expressão, denominada de condição de não-negatividade:

$$
\begin{align*}
x_1 &\geq 0 \\
x_2 &\geq 0 
\end{align*}
$$

# Formulação genérica:

## índices/conjuntos:

$$
I \colon \text{Conjunto de recursos disponiveis(tempo, equipamentos, etc.), nesse caso, o tempo dedicado ao manejo}, \{1, \dots, m\}
$$

$$
J \colon \text{Conjunto de tipos de florestas (nativa, plantada, etc.)}, \{1, \ldots, n\}
$$

## Parâmetros:

$$
c_j \colon \text{receita por hectare do tipo de floresta } j \in J
$$

$$
a_{ij} \colon \text{quantidade do recurso } i  \text{(dias/ha) exigida para o manejo do tipo } j \in J 
$$

$$
A_j \colon \text{area maxima disponivel do tipo de floresta } j \in J
$$

$$
b_i \colon \text{quantidade total disponivel do recurso } i
$$

## Variáveis de decisão:

$$
x_j \colon \text{quantidade de hectares } j \in J \text{ a serem manejados por ano}
$$

## Modelo matemático:

$$
\max z = \sum_{j \in J} c_j x_j
$$

$$
\text{s.a}
$$

$$
\sum_{j \in J} a_{ij} x_j \leq b_i, \quad \forall\, i \in I
$$

$$
x_j \leq A_j, \quad \forall\ j \in J 
$$

$$
x_j \geq 0, \quad \forall\ j \in J 
$$

## Dados de entrada:

```{python}

# vetor de receita por tipo de floresta
receita = [90, 120] 

# matriz de quantidade recursos exigida para cada manejo
tempo_por_manejo = [
  [2, 3]
]

# vetor de área máxima
area_max = [40, 50]

# vetor de recurso máximo
tempo_maximo = [180]

# quantidade de recursos
n_total_recursos = len(tempo_por_manejo)

# quantidade de florestas a serem manejadas
n_tipos_florestas = len(receita)
```

# Resolução do problema

## 1. Importar bibliotecas

```{python}
import pyomo.environ as pyo
```

## 2. Importar e definir solver

```{python}
# solver = pyo.SolverFactory("glpk")

# windows
solver = pyo.SolverFactory(
    _name="glpk", 
    executable="C:/Users/klmp00145394/Documents/glpk-4.65/w64/glpsol.exe"
)
```

## 3. Declarar modelo

```{python}
modelo = pyo.ConcreteModel()
```

## 4. Declarar índices, parâmetros e variáveis de decisão

### 4.1 Índices

```{python}
modelo.I_recursos = range(n_total_recursos)
modelo.J_tipos_de_floresta = range(n_tipos_florestas)
```

### 4.2 Parâmetros

```{python}
# sintaxe de um dicionário:
# {chave: valor for item in interável}

# %% Receita por tipo de floresta ==================================

# criar dicionário
dict_receita = {j: receita[j] for j in modelo.J_tipos_de_floresta}

# declara o parâmetro no modelo
modelo.c_receita = pyo.Param(
  modelo.J_tipos_de_floresta,
  initialize = dict_receita
)


# %% Quantidade do recurso i exigida para o manejo do tipo de floresta j =============

# criar o dicionário
dict_recurso_x_tipo_floresta = {
  (i, j): tempo_por_manejo[i][j] 
  for i in modelo.I_recursos
  for j in modelo.J_tipos_de_floresta
}

# declarar o parâmetro no modelo
modelo.a_recursos_x_floresta = pyo.Param(
  modelo.I_recursos,
  modelo.J_tipos_de_floresta,
  initialize = dict_recurso_x_tipo_floresta
)


# %% Área máxima disponível por tipo de floresta j ==================

# criar o dicionário
dict_area_maxima = {j: area_max[j] for j in modelo.J_tipos_de_floresta}

# declarar o parâmetro no modelo
modelo.area_maxima = pyo.Param(
  modelo.J_tipos_de_floresta,
  initialize = dict_area_maxima
)

# %% Quantidade total do recurso i ==================================

# criar o dicionário
dict_limite_recurso = {b: tempo_maximo[b] for b in modelo.I_recursos}

# declarar o par6ametro no modelo
modelo.lim_recurso = pyo.Param(
  modelo.I_recursos,
  initialize = dict_limite_recurso
)
```

### 4.3 Variáveis de decisão

```{python}
# as variáveis estão associadas ao conjunto J (tipos de florestas) e não podem ser negativas
modelo.x_variaveis = pyo.Var(
  modelo.J_tipos_de_floresta,
  within = pyo.NonNegativeReals
)
```

## 5. Declarar funsção objetivo

```{python}
# criar função de apoio para calcular a receita
def regra_funcao_z(mod):
  # 1. calcula a receita total: receita do tipo de floresta manejado (R$/ha) * x hectares
  receita_total = sum(
    mod.c_receita[j] * mod.x_variaveis[j]
    for j in mod.J_tipos_de_floresta
  )

  # 2. retorna o resultaado
  return receita_total

  
# declarar função objetivo
modelo.z = pyo.Objective(
  rule = regra_funcao_z,
  sense = pyo.maximize
)
```

## 6. Declarar restrições

```{python}

# criar função para limitar a quantidade de área por tipo de floresta para cada variável
def regra_area_maxima(mod, j):
  return mod.x_variaveis[j] <= mod.area_maxima[j]

# declarar restrição
modelo.restricao_area_maxima = pyo.Constraint(
  modelo.J_tipos_de_floresta, # sempre relacionar a restrição com os conjuntos
  rule = regra_area_maxima
)

  
# criar função para checar o limite de recurso usado (tempo)
def regra_tempo_disponivel(mod, recurso_i):
  horas_totais = sum(
    mod.a_recursos_x_floresta[recurso_i, j] * mod.x_variaveis[j]
    for j in mod.J_tipos_de_floresta
  )

  return horas_totais <= mod.lim_recurso[recurso_i]
    
# declarar restrição
modelo.restricao_limite_recurso = pyo.Constraint(
  modelo.I_recursos,  # sempre relacionar a restrição com os conjuntos
  rule = regra_tempo_disponivel
)

```

## 7. Resolver modelo

```{python}
# ver modelo
modelo.pprint()

# resolver modelo
resultado = solver.solve(modelo)

```

## 8. Exportar resultados

```{python}

# resultado bruto do modelo
resultado.write

# Função objetivo
print(f"Receita máxima (z) = R${pyo.value(modelo.z):.2f}")

# :.2f
# : -> iniciar formatação
# .2 -> duas casas decimais
# f -> tipo float
# equilalente à: format(pyo.value(modelo.z), ".2f")


# tipos de floresta
nome_tipos = {
  0: "Pinus",
  1: "Nativa"
}

for j in modelo.J_tipos_de_floresta:
  nome = nome_tipos[j]
  valor = modelo.x_variaveis[j].value
  print(f"Área manejada de {nome}: {valor:.2f} ha")


```